### ISSUE TITLE
[Idea] Add an option for system-wide user specific salt

### ISSUE THREAD

**Issue by seebaclo** [neithernut/pam_e4crypt#12]
I'm sorry for constantly disturbing you but I wanted to share one more idea :)

Currently user can set her specific salt in` ~/.ext4_encryption_salt` which is unfortunately incompatible with encrypted `$HOME` directory. My idea is to add option to set system-wide salt directory like `/var/e4crypt` or `/home/.e4crypt`  where pam_e4crypt will look for user salts instead taking precedence.

This option could be like this:
`salt_path=$PATHNAME`

User could setup it like this:
```
auth        required        pam_e4crypt.so salt_path=${PATHNAME}
session     required        pam_e4crypt.so salt_path=${PATHNAME}
```
I'm not sure if it needs to be set for both `auth` and `session` or for only one of them.

Now to be available for different users in case of  `salt_path` is set, `pam_e4crypt` will look for `$PATHNAME/$USERNAME-ext4_encryption_salt` file instead of `$HOME/.ext4_encryption_salt` file.

Specific example:
```
auth        required        pam_e4crypt.so salt_path=/var/e4crypt
session     required        pam_e4crypt.so salt_path=/var/e4crypt
```
For user **Bob** pam_e4crypt uses salt from `/var/e4crypt/Bob-ext4_encryption_salt`
For user **Alice** pam_e4crypt uses salt from `/var/e4crypt/Alice-ext4_encryption_salt`

Unfortunately I can't help implementing this due to lack of programming skill but I can show you implementation of similar option in [pam_yubico](https://github.com/Yubico/yubico-pam/tree/f3fc6e4c1a0068810045bcd898f5df8aba6d8692) module. In this case the option name is [chalresp_path](https://github.com/Yubico/yubico-pam/search?q=chalresp_path&type=Code&utf8=%E2%9C%93) and it overrides default `$HOME/.yubico/`

I hope above will help you in some way. What do you think about this?

**Comment by neithernut** [comment]
I'll consider it.

**Comment by seebaclo** [comment]
As a side-note, because I don't know if new issue is really needed:

The  example command from readme: 
```text
echo -n `head -c 16 /dev/urandom | xxd -p` > ~/.ext4_encryption_salt` 
```
like `e8657e0767ca4b326b9cba521e51e77d` isn't accepted as salt by `pam_e4crpt` as it says it's invalid.

[The proper command should look like ](https://github.com/neithernut/pam_e4crypt/commit/a77d7f9fecf915676c9e1ca788324d94b725f5a7)
```text
`echo -n s:`head -c 16 /dev/urandom | xxd -p` > ~/.ext4_encryption_salt` 
```
(note missing **s:** ).

Also adding custom salt didn't stop `pam_e4crypt` from using all other salts from all ext4 partitions. This results in bunch of keys in user keyring and you can't say which is which without looking for logs.

I think using custom salt should block from automatically using other salts to add keys because it creates confusion and could lead to mistakes like encrypting dir with wrong key. One of the reasons for using custom salt is to avoid such issues.

**Comment by neithernut** [comment]
Shame on me for not checking the README enough before emerging. I'll give you the change to open a PR correcting the README. If I don't see one until tomorrow, I'll open one myself.

As for non-custom salts: there are valid use-cases where you want a custom and a system key. Blocking system-wide keys is not a thing I'd like as a default. Rather, we should introduce ways to communicate to the user which key is salted from what source. But that's another issue.

**Comment by seebaclo** [comment]
A this issue isn't resolved for now, could you give me a tip how to change default salt directory for my own usage?

I see this line of code:
`snprintf(path, PATH_MAX, "%s/%s", pw->pw_dir, ".ext4_encryption_salt");`
Which results in salt dir = `/home/user/.ext4_encryption_salt`
I wanted to change it to: `/home/.ext4_encryption_salt`

How to do this?

**Comment by neithernut** [comment]
Exchange `pw->pw_dir` with `"/home"`.

**Comment by seebaclo** [comment]
Works, thank you. My system really doesn't like `/home` encrypted this way  :smile:
