### ISSUE TITLE
[info] fscrypt by google

### ISSUE THREAD

**Issue by ghost** [neithernut/pam_e4crypt#19]
There is new fscrypt tool https://github.com/google/fscrypt with pending PR to add pam integration https://github.com/google/fscrypt/pull/25 . It has `drop_caches` option which would solve https://github.com/neithernut/pam_e4crypt/issues/11 , see https://github.com/google/fscrypt/pull/25/files#diff-04c6e90faac2675aa89e2176d2eec7d8R194 and probably many more features suitable for pam_e4crypt

**Comment by neithernut** [comment]
Thanks for the hint. Maybe I'll refer to fscrypt in the README.

----

Reading some of the stuff, I realized I didn't yet probably address passphrase changes. I always had it in mind but I never actually documented the issue.
