### ISSUE TITLE
Is the 16-byte salt length required ?

### ISSUE THREAD

**Issue by blob42** [neithernut/pam_e4crypt#35]
I used a custom salt that was not a fixed 16 bytes length and it still worked. Also in the code I see nowhere where there is a hard check for the 16-byte length, is there a reason for keeping this detail on the README ?

**Comment by neithernut** [comment]
Looks like I made an error when writing that section. Thanks for pointing it out! I'll fix the offending sentence soonish.

The salt must be provided, but its length may be smaller than 16 bytes. This constant (`EXT4_MAX_SALT_SIZE` in the code) is the maximum salt length. If the salt-file is larger, the module will not complain but just ignore the extra contents. At least for now.

**Comment by blob42** [comment]
All right no problem. Thanks for this useful module :)

On May 2, 2019 2:58:23 PM GMT+02:00, Julian Ganz <notifications@github.com> wrote:
>Looks like I made an error when writing that section. Thanks for
>pointing it out! I'll fix the offending sentence soonish.
>
>The salt must be provided, but its length may be smaller than 16 bytes.
>This constant (`EXT4_MAX_SALT_SIZE` in the code) is the maximum salt
>length. If the salt-file is larger, the module will not complain but
>just ignore the extra contents. At least for now.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/neithernut/pam_e4crypt/issues/35#issuecomment-488662371

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
